language: csharp
solution: server.sln
dotnet: 2.1
before_install:
  - sudo apt-get install nuget
install:
  - nuget restore server/server.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet test server/server.sln
