language: csharp
solution: server.sln
mono: none
dotnet: 2.1
install:
  - nuget restore server.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet test server/server.sln
notifications:
    slack: luthercs:28A3oEVAuBP0dVDsQWLKAZHh
