// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pluggedIn_entity.Models;

namespace pluggedIn_entity.Migrations
{
    [DbContext(typeof(PluggedContext))]
    partial class PluggedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pluggedIn_entity.Models.Audition", b =>
                {
                    b.Property<int>("AuditionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Audition_Description");

                    b.Property<string>("Audition_Location");

                    b.Property<DateTime>("Closed_Date");

                    b.Property<int>("EnsembleId");

                    b.Property<string>("Instrument_Name");

                    b.Property<DateTime>("Open_Date");

                    b.HasKey("AuditionId");

                    b.HasIndex("EnsembleId");

                    b.ToTable("Audition");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Booked_Gig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Booked");

                    b.Property<int>("GigId");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("Booked_Gig");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Ensemble", b =>
                {
                    b.Property<int>("EnsembleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Disbanded_Date");

                    b.Property<string>("Ensemble_Name");

                    b.Property<DateTime>("Formed_Date");

                    b.Property<string>("Genre");

                    b.Property<string>("Pic_Url");

                    b.Property<string>("Type");

                    b.Property<int>("UserId");

                    b.HasKey("EnsembleId");

                    b.HasIndex("UserId");

                    b.ToTable("Ensemble");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Gig", b =>
                {
                    b.Property<int>("GigId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Gig_Date");

                    b.Property<int>("VenueId");

                    b.HasKey("GigId");

                    b.HasIndex("VenueId");

                    b.ToTable("Gig");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Instrument_Name");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Plays_Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InstrumentId");

                    b.Property<int?>("ProfileId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("Plays_Instrument");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First_Name");

                    b.Property<string>("Last_Name");

                    b.Property<string>("Pic_Url");

                    b.Property<string>("Preferred_Name");

                    b.Property<int>("UserId");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location");

                    b.Property<int>("UserId");

                    b.Property<string>("Venue_Name");

                    b.HasKey("VenueId");

                    b.HasIndex("UserId");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Audition", b =>
                {
                    b.HasOne("pluggedIn_entity.Models.Ensemble", "Ensemble")
                        .WithMany("Audition")
                        .HasForeignKey("EnsembleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Booked_Gig", b =>
                {
                    b.HasOne("pluggedIn_entity.Models.Gig", "Gig")
                        .WithMany("Booked_Gig")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Ensemble", b =>
                {
                    b.HasOne("pluggedIn_entity.Models.User", "User")
                        .WithMany("Ensemble")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Gig", b =>
                {
                    b.HasOne("pluggedIn_entity.Models.Venue", "Venue")
                        .WithMany("Gig")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Plays_Instrument", b =>
                {
                    b.HasOne("pluggedIn_entity.Models.Instrument", "Instrument")
                        .WithMany("Plays_Instrument")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pluggedIn_entity.Models.Profile")
                        .WithMany("Plays_Instrument")
                        .HasForeignKey("ProfileId");

                    b.HasOne("pluggedIn_entity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Profile", b =>
                {
                    b.HasOne("pluggedIn_entity.Models.User", "User")
                        .WithMany("Profile")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pluggedIn_entity.Models.Venue", b =>
                {
                    b.HasOne("pluggedIn_entity.Models.User", "User")
                        .WithMany("Venue")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
